# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@eslint/eslintrc-1.0.3" = {
      name = "_at_eslint_slash_eslintrc";
      packageName = "@eslint/eslintrc";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@eslint/eslintrc/-/eslintrc-1.0.3.tgz";
        sha512 = "DHI1wDPoKCBPoLZA3qDR91+3te/wDSc1YhKg3jR8NxKKRJq2hwHwcWv31cSwSYvIBrmbENoYMWcenW8uproQqg==";
      };
    };
    "@humanwhocodes/config-array-0.6.0" = {
      name = "_at_humanwhocodes_slash_config-array";
      packageName = "@humanwhocodes/config-array";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@humanwhocodes/config-array/-/config-array-0.6.0.tgz";
        sha512 = "JQlEKbcgEUjBFhLIF4iqM7u/9lwgHRBcpHrmUNCALK0Q3amXN6lxdoXLnF0sm11E9VqTmBALR87IlUg1bZ8A9A==";
      };
    };
    "@humanwhocodes/object-schema-1.2.0" = {
      name = "_at_humanwhocodes_slash_object-schema";
      packageName = "@humanwhocodes/object-schema";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@humanwhocodes/object-schema/-/object-schema-1.2.0.tgz";
        sha512 = "wdppn25U8z/2yiaT6YGquE6X8sSv7hNMWSXYSSU1jGv/yd6XqjXgTDJ8KP4NgjTXfJ3GbRjeeb8RTV7a/VpM+w==";
      };
    };
    "@iarna/toml-2.2.5" = {
      name = "_at_iarna_slash_toml";
      packageName = "@iarna/toml";
      version = "2.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@iarna/toml/-/toml-2.2.5.tgz";
        sha512 = "trnsAYxU3xnS1gPHPyU961coFyLkh4gAD/0zQ5mymY4yOZ+CYvsPqUbOFSw0aDM4y0tV7tiFxL/1XfXPNC6IPg==";
      };
    };
    "@msgpack/msgpack-2.7.1" = {
      name = "_at_msgpack_slash_msgpack";
      packageName = "@msgpack/msgpack";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@msgpack/msgpack/-/msgpack-2.7.1.tgz";
        sha512 = "ApwiSL2c9ObewdOE/sqt788P1C5lomBOHyO8nUBCr4ofErBCnYQ003NtJ8lS9OQZc11ximkbmgAZJjB8y6cCdA==";
      };
    };
    "@ot-builder/bin-composite-types-1.3.0" = {
      name = "_at_ot-builder_slash_bin-composite-types";
      packageName = "@ot-builder/bin-composite-types";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/bin-composite-types/-/bin-composite-types-1.3.0.tgz";
        sha512 = "GWjLQGjwCzWyFjeTRsY4nrw7odSA23j/jDB6rTYiFPd2XQ+TDTtsYGAWBWP30llE9Et07bjBHQAYfpJmRcnNYg==";
      };
    };
    "@ot-builder/bin-util-1.3.0" = {
      name = "_at_ot-builder_slash_bin-util";
      packageName = "@ot-builder/bin-util";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/bin-util/-/bin-util-1.3.0.tgz";
        sha512 = "y4kBgfAZfjeOU8rxnCvnlpjoVdydzjvo+PCnY+KaQ5h+naSDUHfvHdQfg6TALW2iyK2VbXYT013SAU4EK/nwng==";
      };
    };
    "@ot-builder/cli-help-shower-1.3.0" = {
      name = "_at_ot-builder_slash_cli-help-shower";
      packageName = "@ot-builder/cli-help-shower";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/cli-help-shower/-/cli-help-shower-1.3.0.tgz";
        sha512 = "t67lnwK1muzmcsj9ytG9xvYsRhnnomfJU8VPh4Mm9N1bjUAmdfkV/PWKrHtXebCpm2bDc+5L/D+fgA0EZ5qgtg==";
      };
    };
    "@ot-builder/cli-proc-1.3.0" = {
      name = "_at_ot-builder_slash_cli-proc";
      packageName = "@ot-builder/cli-proc";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/cli-proc/-/cli-proc-1.3.0.tgz";
        sha512 = "205Vn44R2qQrloAuA4YvrdYMIBxxk/PHRFQICnzP+fyOI01B3yPFUQpKfCNX6l+BzbEfDXJNN6Z/d6WqQuGrJw==";
      };
    };
    "@ot-builder/cli-shared-1.3.0" = {
      name = "_at_ot-builder_slash_cli-shared";
      packageName = "@ot-builder/cli-shared";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/cli-shared/-/cli-shared-1.3.0.tgz";
        sha512 = "pW26ckQ2KngS56uyNjQ9rUYUP0shKzFXu/8JqdlmgxSXbs5M9RTWEHKUIHN/QkDCj7hebmKkDxhqlDFJJWFI+A==";
      };
    };
    "@ot-builder/common-impl-1.3.0" = {
      name = "_at_ot-builder_slash_common-impl";
      packageName = "@ot-builder/common-impl";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/common-impl/-/common-impl-1.3.0.tgz";
        sha512 = "Io96P5AyVF2T44buNevoHDdu0zhGr/buFyKaPBYZ37RdUtTF8B5f7k74I07LWqi9wa0npE3qXQ9GXz3aMrO0IA==";
      };
    };
    "@ot-builder/errors-1.3.0" = {
      name = "_at_ot-builder_slash_errors";
      packageName = "@ot-builder/errors";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/errors/-/errors-1.3.0.tgz";
        sha512 = "pUtbx4ut02Qpy+W3uLblLvZQDH+kZw+i0/IjKyWxSRuzhPrqvV0VjxOoiQFrcDltHg5m2aUsEZFwepiqP7CkJA==";
      };
    };
    "@ot-builder/io-bin-cff-1.3.0" = {
      name = "_at_ot-builder_slash_io-bin-cff";
      packageName = "@ot-builder/io-bin-cff";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-cff/-/io-bin-cff-1.3.0.tgz";
        sha512 = "DvZYigOGZJLnVdO6qJTgCUiInBf1BRspWACWwVNGPCmdbgW5TUR4IQtibV374y8sJp/4AHxORqUefFn6PhG1/A==";
      };
    };
    "@ot-builder/io-bin-encoding-1.3.0" = {
      name = "_at_ot-builder_slash_io-bin-encoding";
      packageName = "@ot-builder/io-bin-encoding";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-encoding/-/io-bin-encoding-1.3.0.tgz";
        sha512 = "0xbnGCtCU7kW20bMA01e1fm0/f4mXsiORHvGd9MtYXxfVfOSqa7s/KFaG7GcjzqNmMAAXHjtrRy0sh8g7bo5CQ==";
      };
    };
    "@ot-builder/io-bin-ext-private-1.3.0" = {
      name = "_at_ot-builder_slash_io-bin-ext-private";
      packageName = "@ot-builder/io-bin-ext-private";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-ext-private/-/io-bin-ext-private-1.3.0.tgz";
        sha512 = "CQHIr0d4fczqvDPJRJkl5tnjKXmj7iktcxBnZTiF8plbFtLjmswv8EZnwyP04BhT3ZgpVZNDANBFb13mO3Sd4g==";
      };
    };
    "@ot-builder/io-bin-font-1.3.0" = {
      name = "_at_ot-builder_slash_io-bin-font";
      packageName = "@ot-builder/io-bin-font";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-font/-/io-bin-font-1.3.0.tgz";
        sha512 = "H8g2kmk0rNTOKQSXbQraOPUxt21Cxjs2uDL+oioth6YpxTOTlL67rOUcx1k32VyaVv/9buLGe0AD/S6qxzrl4g==";
      };
    };
    "@ot-builder/io-bin-glyph-store-1.3.0" = {
      name = "_at_ot-builder_slash_io-bin-glyph-store";
      packageName = "@ot-builder/io-bin-glyph-store";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-glyph-store/-/io-bin-glyph-store-1.3.0.tgz";
        sha512 = "ni127weqUSy2f20V5d21XMNBAavW1ioOwIWRVSVrHQnO4YA+X+SxWy6b48MLa1BlvfQ1vJV0NIvBZ+2jD0PQig==";
      };
    };
    "@ot-builder/io-bin-layout-1.3.0" = {
      name = "_at_ot-builder_slash_io-bin-layout";
      packageName = "@ot-builder/io-bin-layout";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-layout/-/io-bin-layout-1.3.0.tgz";
        sha512 = "lrBlkmaOretCG1zQarLNW9Us8tZ2L1RI2DPYW5oidRzbGRV7NxhScgUGCbPi+AWYCX+2paCiiy/6XLARsq2XCA==";
      };
    };
    "@ot-builder/io-bin-metadata-1.3.0" = {
      name = "_at_ot-builder_slash_io-bin-metadata";
      packageName = "@ot-builder/io-bin-metadata";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-metadata/-/io-bin-metadata-1.3.0.tgz";
        sha512 = "KLQdLISXLB5RzVZJYS7Qp9B3IQkGkjAXvgLD+A8ekfuG+0oc/D2ss9QAeCoikOTJ/g86WODZpIRdP8pAgTj9LA==";
      };
    };
    "@ot-builder/io-bin-metric-1.3.0" = {
      name = "_at_ot-builder_slash_io-bin-metric";
      packageName = "@ot-builder/io-bin-metric";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-metric/-/io-bin-metric-1.3.0.tgz";
        sha512 = "/t85ePUtsud1eUAwNbT5rEaB3vnOseTgTxmYTkFu/WNPJYhSLAtPi4K3SP6vLwALlNlVRMXiNIcaETDsIaNt3g==";
      };
    };
    "@ot-builder/io-bin-name-1.3.0" = {
      name = "_at_ot-builder_slash_io-bin-name";
      packageName = "@ot-builder/io-bin-name";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-name/-/io-bin-name-1.3.0.tgz";
        sha512 = "04lTnQa1Eg6maFyP0WuUTkSLzU4QdcAvh7PYyGDZSdIyg/RPl1g7ymzOyi7P3DGdkH4FNORyS2DJ778v9J5OgA==";
      };
    };
    "@ot-builder/io-bin-sfnt-1.3.0" = {
      name = "_at_ot-builder_slash_io-bin-sfnt";
      packageName = "@ot-builder/io-bin-sfnt";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-sfnt/-/io-bin-sfnt-1.3.0.tgz";
        sha512 = "9a/VKD5JlRGEDsM1I0boismi27TrSl8sHJXoPoBh3EFtatLRbbgcYp4fs2UJYp/pvpIT4k0Ti0gp5e4Q7z08eA==";
      };
    };
    "@ot-builder/io-bin-ttf-1.3.0" = {
      name = "_at_ot-builder_slash_io-bin-ttf";
      packageName = "@ot-builder/io-bin-ttf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-ttf/-/io-bin-ttf-1.3.0.tgz";
        sha512 = "RLvDBBTVkInXtC9hpl8oi30DudL4oy41FUEMOoCYyWpw8tvcSOpEyqHtf46X3ehC8IdPQIsGMRRchyZFOUclZw==";
      };
    };
    "@ot-builder/io-bin-vtt-private-1.3.0" = {
      name = "_at_ot-builder_slash_io-bin-vtt-private";
      packageName = "@ot-builder/io-bin-vtt-private";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/io-bin-vtt-private/-/io-bin-vtt-private-1.3.0.tgz";
        sha512 = "ZLUmXlwX3Oc83QPUUCLMlnnhyEMmN+iscyagA1fWGYyPqjagRpTAet5PVSpSkdIqosT3QZw2eZBxzrXUHB4eqw==";
      };
    };
    "@ot-builder/ot-1.3.0" = {
      name = "_at_ot-builder_slash_ot";
      packageName = "@ot-builder/ot";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot/-/ot-1.3.0.tgz";
        sha512 = "8tnizbMO9o905/SLC1eEr8VQBKssGDDPiSSiUCA8f00gzLkrrTjpV4zgv9LSEY5YL260e0yEbg4IlZcJwtGBJA==";
      };
    };
    "@ot-builder/ot-encoding-1.3.0" = {
      name = "_at_ot-builder_slash_ot-encoding";
      packageName = "@ot-builder/ot-encoding";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-encoding/-/ot-encoding-1.3.0.tgz";
        sha512 = "rLndCSJj11TsOvlPumcwfJKqJCyx4FEV+rn6rjKGXCpSeeSrNWhLIyCBZThXwJwCNY2OdqZtl8My3/xefS3H7g==";
      };
    };
    "@ot-builder/ot-ext-private-1.3.0" = {
      name = "_at_ot-builder_slash_ot-ext-private";
      packageName = "@ot-builder/ot-ext-private";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-ext-private/-/ot-ext-private-1.3.0.tgz";
        sha512 = "Tiie59wQvM8ZRtTrprjuHrrsQ2YBI2mTMFzzro6L+q4glMqzFi2nkGrBapd6Z9dx8x7TI8NGiEjlbjefEhx0RQ==";
      };
    };
    "@ot-builder/ot-glyphs-1.3.0" = {
      name = "_at_ot-builder_slash_ot-glyphs";
      packageName = "@ot-builder/ot-glyphs";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-glyphs/-/ot-glyphs-1.3.0.tgz";
        sha512 = "NXXcqydqoZ2+9fvam/5ybWdWAXL6JIyCQQluMuRMYvtT0GrZE/D7q2C/h0wiDI2PWljMS1wRl855A8fryHIOfg==";
      };
    };
    "@ot-builder/ot-layout-1.3.0" = {
      name = "_at_ot-builder_slash_ot-layout";
      packageName = "@ot-builder/ot-layout";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-layout/-/ot-layout-1.3.0.tgz";
        sha512 = "Cifx79+3GjtFouzwL6IlEMMDIk5n2KmSNeNi2ZSy9mIpHmu6MU62UTQZGs2WmTIuLcRv2CQuQnN/kLlNHt9d4A==";
      };
    };
    "@ot-builder/ot-metadata-1.3.0" = {
      name = "_at_ot-builder_slash_ot-metadata";
      packageName = "@ot-builder/ot-metadata";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-metadata/-/ot-metadata-1.3.0.tgz";
        sha512 = "Qxb+vKKKmlnlIujvp/0ag1P4zqW3lFZ2D/WXbUJWunf2vQMLAkcPWI7qJy7ZNHDIcvT0Nva/JuXpbuKiQWarwg==";
      };
    };
    "@ot-builder/ot-name-1.3.0" = {
      name = "_at_ot-builder_slash_ot-name";
      packageName = "@ot-builder/ot-name";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-name/-/ot-name-1.3.0.tgz";
        sha512 = "EKLpWujBo5Gg8SM6ENzXmsezGSMAyKRTBucdYwM8Dkt41q1rnTJiZKkF7clC2uBO2jCeTIxRlan9yergdaPWzg==";
      };
    };
    "@ot-builder/ot-sfnt-1.3.0" = {
      name = "_at_ot-builder_slash_ot-sfnt";
      packageName = "@ot-builder/ot-sfnt";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-sfnt/-/ot-sfnt-1.3.0.tgz";
        sha512 = "8ZQUlp/ox5OKrpCgueTfplag2bw4GQ9qqrsC/hGxXwFzcJxS/o1OIwfpkV/Rx7A4Edx4jn/Ts8Y/C67AGYPlpQ==";
      };
    };
    "@ot-builder/ot-standard-glyph-namer-1.3.0" = {
      name = "_at_ot-builder_slash_ot-standard-glyph-namer";
      packageName = "@ot-builder/ot-standard-glyph-namer";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-standard-glyph-namer/-/ot-standard-glyph-namer-1.3.0.tgz";
        sha512 = "tKYXVcpaGTZSGypiqnYIZASzDrQhh6AVmu7fN1AUfGYmI8AMnPVC4osdksRpCTmi4HcgfMp4osichTGSJVpCWw==";
      };
    };
    "@ot-builder/ot-vtt-private-1.3.0" = {
      name = "_at_ot-builder_slash_ot-vtt-private";
      packageName = "@ot-builder/ot-vtt-private";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/ot-vtt-private/-/ot-vtt-private-1.3.0.tgz";
        sha512 = "RdhTIYoDUjkyZk7ZmMjRx0rT0KrcdHedmLvLQtmB3tYD+0NQlNLJuLkKDBbcTHZwW05aY/gdN0Yv2wbxfQaryg==";
      };
    };
    "@ot-builder/prelude-1.3.0" = {
      name = "_at_ot-builder_slash_prelude";
      packageName = "@ot-builder/prelude";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/prelude/-/prelude-1.3.0.tgz";
        sha512 = "E4LvaFA74YEKNFkzmbCyiooV31e1p/16Ajr8/Pvf8OlQGSGf0UkbZVOikpdJZBTr4kL6mpQsGRAo+xJHmeIviw==";
      };
    };
    "@ot-builder/primitive-1.3.0" = {
      name = "_at_ot-builder_slash_primitive";
      packageName = "@ot-builder/primitive";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/primitive/-/primitive-1.3.0.tgz";
        sha512 = "KqVxt5YdH/1gusrUAenytoo+MtzSg2YyXHXBfdP9YLL5HE72gG6irVJy1eQFXr4RsZ8GVhhguIrvRZ0gMbnAPw==";
      };
    };
    "@ot-builder/rectify-1.3.0" = {
      name = "_at_ot-builder_slash_rectify";
      packageName = "@ot-builder/rectify";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/rectify/-/rectify-1.3.0.tgz";
        sha512 = "b3xNK7gTwNa5AFoiFL3cjLcqBk0vHfGrkKcbApImSM74KDUkAGK9ZeefrI1snFzIFmnWFWu5o86+DB2u/1PV8Q==";
      };
    };
    "@ot-builder/stat-glyphs-1.3.0" = {
      name = "_at_ot-builder_slash_stat-glyphs";
      packageName = "@ot-builder/stat-glyphs";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/stat-glyphs/-/stat-glyphs-1.3.0.tgz";
        sha512 = "TQqinShddh7lBkQMQxZV9Ry4HJGsFUThgIWanh1ztVp9wJjPiXuJN+G8d/ryQflO5syGGioAMQjMsojLIQDG1g==";
      };
    };
    "@ot-builder/trace-1.3.0" = {
      name = "_at_ot-builder_slash_trace";
      packageName = "@ot-builder/trace";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/trace/-/trace-1.3.0.tgz";
        sha512 = "EPHE78+L9mH4rBMkA/Ac+qMW/xLYTpNonxeMHzT+AxZ4ixz1gTY0LU9JtkkG+sdby3sLSLwAKPDaqFYQCQ1B3Q==";
      };
    };
    "@ot-builder/var-store-1.3.0" = {
      name = "_at_ot-builder_slash_var-store";
      packageName = "@ot-builder/var-store";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/var-store/-/var-store-1.3.0.tgz";
        sha512 = "7wuUX8GlosMhOU92xClWBUELkKtpszsouuPAZQsbHIoz4WaUUEYfVwpTB1Xcj3UA0M/eTSmM1rIlB0SFJ2jywQ==";
      };
    };
    "@ot-builder/variance-1.3.0" = {
      name = "_at_ot-builder_slash_variance";
      packageName = "@ot-builder/variance";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ot-builder/variance/-/variance-1.3.0.tgz";
        sha512 = "snCKMC8X/HIJVmcqAiRSmA7LtJyDFxaBshIzqOxWYC4X8rLwcMOzpiKLGCdxIpJq38vbmb3QS9WZmjrzgKMN8w==";
      };
    };
    "@unicode/unicode-13.0.0-1.2.1" = {
      name = "_at_unicode_slash_unicode-13.0.0";
      packageName = "@unicode/unicode-13.0.0";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unicode/unicode-13.0.0/-/unicode-13.0.0-1.2.1.tgz";
        sha512 = "8NDE4zZASktxJe+hV13K795wefyx+wRhu3Wl7TJ8fzsKx95CHsgTFmYRTscqna90zpUz6YBjGyqXHBI2ubiMaw==";
      };
    };
    "@xmldom/xmldom-0.7.5" = {
      name = "_at_xmldom_slash_xmldom";
      packageName = "@xmldom/xmldom";
      version = "0.7.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xmldom/xmldom/-/xmldom-0.7.5.tgz";
        sha512 = "V3BIhmY36fXZ1OtVcI9W+FxQqxVLsPKcNjWigIaa81dLC9IolJl5Mt4Cvhmr0flUnjSpTdrbMTSbXqYqV5dT6A==";
      };
    };
    "acorn-8.5.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.5.0.tgz";
        sha512 = "yXbYeFy+jUuYd3/CDcg2NkIYE991XYX/bje7LmjJigUciaeO1JR4XxXgCIV1/Zc/dRuFEyw1L0pbA+qynJkW5Q==";
      };
    };
    "acorn-jsx-5.3.2" = {
      name = "acorn-jsx";
      packageName = "acorn-jsx";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-jsx/-/acorn-jsx-5.3.2.tgz";
        sha512 = "rq9s+JNhf0IChjtDXxllJ7g41oZk5SlXtp0LHwyA5cejwn7vKmKp4pPri6YEePv2PU65sAsegbXtIinmDFDXgQ==";
      };
    };
    "aglfn-1.0.2" = {
      name = "aglfn";
      packageName = "aglfn";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/aglfn/-/aglfn-1.0.2.tgz";
        sha512 = "HUvXd7sNFa1aHtYgJnln2jPwzq7UAAOXhYH/+AY6BMdfXxprMxG8IrczlZn6MjjIWpYhpKR5mHwDWTgehZKO4g==";
      };
    };
    "ajv-6.12.6" = {
      name = "ajv";
      packageName = "ajv";
      version = "6.12.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-6.12.6.tgz";
        sha512 = "j3fVLgvTo527anyYyJOGTYJbG+vnnQYvE0m5mmkc1TK+nxAppkCLMIL0aZ4dblVCNoGShhm+kzE4ZUykBoMg4g==";
      };
    };
    "amdefine-1.0.1" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz";
        sha1 = "4a5282ac164729e93619bcfd3ad151f817ce91f5";
      };
    };
    "ansi-colors-4.1.1" = {
      name = "ansi-colors";
      packageName = "ansi-colors";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-colors/-/ansi-colors-4.1.1.tgz";
        sha512 = "JoX0apGbHaUJBNl6yF+p6JAFYZ666/hhCGKN5t9QFjbJQKUU/g8MNbFDbvfrgKXvI1QpZplPOnwIo99lX/AAmA==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "argparse-2.0.1" = {
      name = "argparse";
      packageName = "argparse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
        sha512 = "8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
      };
    };
    "async-0.9.2" = {
      name = "async";
      packageName = "async";
      version = "0.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.9.2.tgz";
        sha1 = "aea74d5e61c1f899613bf64bda66d4c78f2fd17d";
      };
    };
    "atob-2.1.2" = {
      name = "atob";
      packageName = "atob";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/atob/-/atob-2.1.2.tgz";
        sha512 = "Wm6ukoaOGJi/73p/cl2GvLjTI5JM1k/O14isD73YML8StrH/7/lRFgmg8nICZgD3bZZvjwCGxtMOD3wWNAu8cg==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "callsites-3.1.0" = {
      name = "callsites";
      packageName = "callsites";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsites/-/callsites-3.1.0.tgz";
        sha512 = "P8BjAsXvZS+VIDUI11hHCQEv74YT67YUi5JJFNWIqL235sBmjX4+qx9Muvls5ivyNENctx46xQLQ3aTuE7ssaQ==";
      };
    };
    "chainsaw-0.0.9" = {
      name = "chainsaw";
      packageName = "chainsaw";
      version = "0.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/chainsaw/-/chainsaw-0.0.9.tgz";
        sha1 = "11a05102d1c4c785b6d0415d336d5a3a1612913e";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "cldr-7.1.1" = {
      name = "cldr";
      packageName = "cldr";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cldr/-/cldr-7.1.1.tgz";
        sha512 = "zHHQLSZT9i/g7wAxGrMj1BRD7JYOSJHvPIT06EFkFEl4m9ItW48i9yWqgRgWESJ5oUqLs9IuMDoKf+21Lscqrg==";
      };
    };
    "cli-cursor-3.1.0" = {
      name = "cli-cursor";
      packageName = "cli-cursor";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-3.1.0.tgz";
        sha512 = "I/zHAwsKf9FqGoXM4WWRACob9+SNukZTd94DWF57E4toouRulbCxcUh6RKUEOQlYTHJnzkPMySvPNaaSLNfLZw==";
      };
    };
    "clipper-lib-6.4.2" = {
      name = "clipper-lib";
      packageName = "clipper-lib";
      version = "6.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clipper-lib/-/clipper-lib-6.4.2.tgz";
        sha512 = "knglhjQX5ihNj/XCIs6zCHrTemdvHY3LPZP9XB2nq2/3igyYMFueFXtfp84baJvEE+f8pO1ZS4UVeEgmLnAprQ==";
      };
    };
    "cliui-7.0.4" = {
      name = "cliui";
      packageName = "cliui";
      version = "7.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-7.0.4.tgz";
        sha512 = "OcRE68cOsVMXp1Yvonl/fzkQOyjLSu/8bhPDfQt0e0/Eb283TKP20Fs2MqoPsr9SwA595rRCA+QMzYc9nBP+JQ==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "cross-spawn-7.0.3" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz";
        sha512 = "iRDPJKUPVEND7dHPO8rkbOnPpyDygcDFtWjpeWNCgy8WP2rXcxXL8TskReQl6OrB2G7+UJrags1q15Fudc7G6w==";
      };
    };
    "css-3.0.0" = {
      name = "css";
      packageName = "css";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css/-/css-3.0.0.tgz";
        sha512 = "DG9pFfwOrzc+hawpmqX/dHYHJG+Bsdb0klhyi1sDneOgGOXy9wQIC8hzyVp1e4NRYDBdxcylvywPkkXCHAzTyQ==";
      };
    };
    "debug-3.1.0" = {
      name = "debug";
      packageName = "debug";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz";
        sha512 = "OX8XqP7/1a9cqkxYw2yXss15f26NKWBpDXQd0/uK/KPqdQhxbPa994hnzjcE2VqQpDslf55723cKPUOGSmMY3g==";
      };
    };
    "debug-4.3.2" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.2.tgz";
        sha512 = "mOp8wKcvj7XxC78zLgw/ZA+6TSgkoE2C/ienthhRD298T7UNwAg9diBpLRxC0mOezLl4B0xV7M0cCO6P/O0Xhw==";
      };
    };
    "decode-uri-component-0.2.0" = {
      name = "decode-uri-component";
      packageName = "decode-uri-component";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decode-uri-component/-/decode-uri-component-0.2.0.tgz";
        sha1 = "eb3913333458775cb84cd1a1fae062106bb87545";
      };
    };
    "deep-is-0.1.4" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.4.tgz";
        sha512 = "oIPzksmTg4/MriiaYGO+okXDT7ztn/w3Eptv/+gSIdMdKsJo0u4CfYNFJPy+4SKMuCqGw2wxnA+URMg3t8a/bQ==";
      };
    };
    "doctrine-3.0.0" = {
      name = "doctrine";
      packageName = "doctrine";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/doctrine/-/doctrine-3.0.0.tgz";
        sha512 = "yS+Q5i3hBf7GBkd4KG8a7eBNNWNGLTaEwwYWUijIYM7zrlYDM0BFXHjjPWlWZ1Rg7UaddZeIDmi9jF3HmqiQ2w==";
      };
    };
    "ejs-3.1.6" = {
      name = "ejs";
      packageName = "ejs";
      version = "3.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ejs/-/ejs-3.1.6.tgz";
        sha512 = "9lt9Zse4hPucPkoP7FHDF0LQAlGyF9JVpnClFLFH3aSSbxmyoqINRpp/9wePWJTUl4KOQwRL72Iw3InHPDkoGw==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "enquirer-2.3.6" = {
      name = "enquirer";
      packageName = "enquirer";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/enquirer/-/enquirer-2.3.6.tgz";
        sha512 = "yjNnPr315/FjS4zIsUxYguYUPP2e1NK4d7E7ZOLiyYCcbFBiTMyID+2wvm2w6+pZ/odMA7cRkjhsPbltwBOrLg==";
      };
    };
    "escalade-3.1.1" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz";
        sha512 = "k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "escape-string-regexp-4.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-4.0.0.tgz";
        sha512 = "TtpcNJ3XAzx3Gq8sWRzJaVajRs0uVxA2YAkdb1jm2YkPz4G6egUFAyA3n5vtEIZefPk5Wa4UXbKuS5fKkJWdgA==";
      };
    };
    "escodegen-1.3.3" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-1.3.3.tgz";
        sha1 = "f024016f5a88e046fd12005055e939802e6c5f23";
      };
    };
    "escodegen-2.0.0" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-2.0.0.tgz";
        sha512 = "mmHKys/C8BFUGI+MAWNcSYoORYLMdPzjrknd2Vc+bUsjN5bXcr8EhrNB+UTqfL1y3I9c4fw2ihgtMPQLBRiQxw==";
      };
    };
    "escope-1.0.3" = {
      name = "escope";
      packageName = "escope";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escope/-/escope-1.0.3.tgz";
        sha1 = "759dce8496c4248fec2d0caaf4108bcf3f1a7f5d";
      };
    };
    "eslint-8.0.1" = {
      name = "eslint";
      packageName = "eslint";
      version = "8.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint/-/eslint-8.0.1.tgz";
        sha512 = "LsgcwZgQ72vZ+SMp4K6pAnk2yFDWL7Ti4pJaRvsZ0Hsw2h8ZjUIW38a9AFn2cZXdBMlScMFYYgsSp4ttFI/0bA==";
      };
    };
    "eslint-config-prettier-8.3.0" = {
      name = "eslint-config-prettier";
      packageName = "eslint-config-prettier";
      version = "8.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-config-prettier/-/eslint-config-prettier-8.3.0.tgz";
        sha512 = "BgZuLUSeKzvlL/VUjx/Yb787VQ26RU3gGjA3iiFvdsp/2bMfVIWUVP7tjxtjS0e+HP409cPlPvNkQloz8C91ew==";
      };
    };
    "eslint-scope-6.0.0" = {
      name = "eslint-scope";
      packageName = "eslint-scope";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-scope/-/eslint-scope-6.0.0.tgz";
        sha512 = "uRDL9MWmQCkaFus8RF5K9/L/2fn+80yoW3jkD53l4shjCh26fCtvJGasxjUqP5OT87SYTxCVA3BwTUzuELx9kA==";
      };
    };
    "eslint-utils-3.0.0" = {
      name = "eslint-utils";
      packageName = "eslint-utils";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-utils/-/eslint-utils-3.0.0.tgz";
        sha512 = "uuQC43IGctw68pJA1RgbQS8/NP7rch6Cwd4j3ZBtgo4/8Flj4eGE7ZYSZRN3iq5pVUv6GPdW5Z1RFleo84uLDA==";
      };
    };
    "eslint-visitor-keys-2.1.0" = {
      name = "eslint-visitor-keys";
      packageName = "eslint-visitor-keys";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-visitor-keys/-/eslint-visitor-keys-2.1.0.tgz";
        sha512 = "0rSmRBzXgDzIsD6mGdJgevzgezI534Cer5L/vyMX0kHzT/jiB43jRhd9YUlMGYLQy2zprNmoT8qasCGtY+QaKw==";
      };
    };
    "eslint-visitor-keys-3.0.0" = {
      name = "eslint-visitor-keys";
      packageName = "eslint-visitor-keys";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-visitor-keys/-/eslint-visitor-keys-3.0.0.tgz";
        sha512 = "mJOZa35trBTb3IyRmo8xmKBZlxf+N7OnUl4+ZhJHs/r+0770Wh/LEACE2pqMGMe27G/4y8P2bYGk4J70IC5k1Q==";
      };
    };
    "esmangle-1.0.1" = {
      name = "esmangle";
      packageName = "esmangle";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esmangle/-/esmangle-1.0.1.tgz";
        sha1 = "d9bb37b8f8eafbf4e6d4ed6b7aa2956abbd3c4c2";
      };
    };
    "espree-9.0.0" = {
      name = "espree";
      packageName = "espree";
      version = "9.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/espree/-/espree-9.0.0.tgz";
        sha512 = "r5EQJcYZ2oaGbeR0jR0fFVijGOcwai07/690YRXLINuhmVeRY4UKSAsQPe/0BNuDgwP7Ophoc1PRsr2E3tkbdQ==";
      };
    };
    "esprima-1.1.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-1.1.1.tgz";
        sha1 = "5b6f1547f4d102e670e140c509be6771d6aeb549";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "esquery-1.4.0" = {
      name = "esquery";
      packageName = "esquery";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esquery/-/esquery-1.4.0.tgz";
        sha512 = "cCDispWt5vHHtwMY2YrAQ4ibFkAL8RbH5YGBnZBc90MolvvfkkQcJro/aZiAQUlQ3qgrYS6D6v8Gc5G5CQsc9w==";
      };
    };
    "esrecurse-4.3.0" = {
      name = "esrecurse";
      packageName = "esrecurse";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esrecurse/-/esrecurse-4.3.0.tgz";
        sha512 = "KmfKL3b6G+RXvP8N1vr3Tq1kL/oCFgn2NYXEtqP8/L3pKapUA4G8cFVaoF3SU323CD4XypR/ffioHmkti6/Tag==";
      };
    };
    "esshorten-1.1.1" = {
      name = "esshorten";
      packageName = "esshorten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esshorten/-/esshorten-1.1.1.tgz";
        sha1 = "174f96b7cc267e46872d814e7db7c290bdff61a9";
      };
    };
    "estraverse-1.5.1" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-1.5.1.tgz";
        sha1 = "867a3e8e58a9f84618afb6c2ddbcd916b7cbaf71";
      };
    };
    "estraverse-2.0.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-2.0.0.tgz";
        sha1 = "5ae46963243600206674ccb24a09e16674fcdca1";
      };
    };
    "estraverse-4.1.1" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.1.1.tgz";
        sha1 = "f6caca728933a850ef90661d0e17982ba47111a2";
      };
    };
    "estraverse-5.2.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-5.2.0.tgz";
        sha512 = "BxbNGGNm0RyRYvUdHpIwv9IWzeM9XClbOxwoATuFdOE7ZE6wHL+HQ5T8hoPM+zHvmKzzsEqhgy0GrQ5X13afiQ==";
      };
    };
    "esutils-1.0.0" = {
      name = "esutils";
      packageName = "esutils";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-1.0.0.tgz";
        sha1 = "8151d358e20c8acc7fb745e7472c0025fe496570";
      };
    };
    "esutils-2.0.3" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.3.tgz";
        sha512 = "kVscqXk4OCp68SZ0dkgEKVi6/8ij300KBWTJq32P/dYeWTSwK41WyTxalN1eRmA5Z9UU/LX9D7FWSmV9SAYx6g==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fast-json-stable-stringify-2.1.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz";
        sha512 = "lhd/wF+Lk98HZoTCtlVraHtfh5XYijIjalXck7saUtuanSDyLMxnHhSXEDJqHxD7msR8D0uCmqlkwjCV8xvwHw==";
      };
    };
    "fast-levenshtein-1.0.7" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-1.0.7.tgz";
        sha1 = "0178dcdee023b92905193af0959e8a7639cfdcb9";
      };
    };
    "fast-levenshtein-2.0.6" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
        sha1 = "3d8a5c66883a16a30ca8643e851f19baa7797917";
      };
    };
    "file-entry-cache-6.0.1" = {
      name = "file-entry-cache";
      packageName = "file-entry-cache";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-entry-cache/-/file-entry-cache-6.0.1.tgz";
        sha512 = "7Gps/XWymbLk2QLYK4NzpMOrYjMhdIxXuIvy2QBsLE6ljuodKvdkWs/cpyJJ3CVIVpH0Oi1Hvg1ovbMzLdFBBg==";
      };
    };
    "filelist-1.0.2" = {
      name = "filelist";
      packageName = "filelist";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/filelist/-/filelist-1.0.2.tgz";
        sha512 = "z7O0IS8Plc39rTCq6i6iHxk43duYOn8uFJiWSewIq0Bww1RNybVHSCjahmcC87ZqAm4OTvFzlzeGu3XAzG1ctQ==";
      };
    };
    "flat-cache-3.0.4" = {
      name = "flat-cache";
      packageName = "flat-cache";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/flat-cache/-/flat-cache-3.0.4.tgz";
        sha512 = "dm9s5Pw7Jc0GvMYbshN6zchCA9RgQlzzEZX3vylR9IqFfS8XciblUXOKfW6SiuJ0e13eDYZoZV5wdrev7P3Nwg==";
      };
    };
    "flatted-3.2.2" = {
      name = "flatted";
      packageName = "flatted";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/flatted/-/flatted-3.2.2.tgz";
        sha512 = "JaTY/wtrcSyvXJl4IMFHPKyFur1sE9AUqc0QnhOaJ0CxHtAoIV8pYDzeEfAaNEtGkOfq4gr3LBFmdXW5mOQFnA==";
      };
    };
    "fs-extra-10.0.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "10.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-10.0.0.tgz";
        sha512 = "C5owb14u9eJwizKGdchcDUQeFtlSHHthBk8pbX9Vc1PFZrLombudjDnNns88aYslCyF6IY5SUw3Roz6xShcEIQ==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "functional-red-black-tree-1.0.1" = {
      name = "functional-red-black-tree";
      packageName = "functional-red-black-tree";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/functional-red-black-tree/-/functional-red-black-tree-1.0.1.tgz";
        sha1 = "1b0ab3bd553b2a0d6399d29c0e3ea0b252078327";
      };
    };
    "get-caller-file-2.0.5" = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz";
        sha512 = "DyFP3BM/3YHTQOCUL/w0OZHR0lpKeGrxotcHWcqNEdnltqFwXVfhEBQ94eIo34AfQpo0rGki4cyIiftY06h2Fg==";
      };
    };
    "glob-7.2.0" = {
      name = "glob";
      packageName = "glob";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.2.0.tgz";
        sha512 = "lmLf6gtyrPq8tTjSmrO94wBeQbFR3HbLHbuyD69wuyQkImp2hWqMGB47OX65FBkPffO641IP9jWa1z4ivqG26Q==";
      };
    };
    "glob-parent-6.0.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-6.0.2.tgz";
        sha512 = "XxwI8EOhVQgWp6iDL+3b0r86f4d6AX6zSU55HfB4ydCEuXLXc5FcYeOu+nnGftS4TEju/11rt4KJPTMgbfmv4A==";
      };
    };
    "globals-13.11.0" = {
      name = "globals";
      packageName = "globals";
      version = "13.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globals/-/globals-13.11.0.tgz";
        sha512 = "08/xrJ7wQjK9kkkRoI3OFUBbLx4f+6x3SGwcPvQ0QH6goFDrOU2oyAWrmh3dJezu65buo+HBMzAMQy6rovVC3g==";
      };
    };
    "graceful-fs-4.2.8" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.8.tgz";
        sha512 = "qkIilPUYcNhJpd33n0GBXTB1MMPp14TxEsEs0pTrsSVucApsYzW5V+Q8Qxhik6KU3evy+qkAAowTByymK0avdg==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "hashish-0.0.4" = {
      name = "hashish";
      packageName = "hashish";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/hashish/-/hashish-0.0.4.tgz";
        sha1 = "6d60bc6ffaf711b6afd60e426d077988014e6554";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "ignore-4.0.6" = {
      name = "ignore";
      packageName = "ignore";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ignore/-/ignore-4.0.6.tgz";
        sha512 = "cyFDKrqc/YdcWFniJhzI42+AzS+gNwmUzOSFcRCQYwySuBBBy/KjuxWLZ/FHEH6Moq1NizMOBWyTcv8O4OZIMg==";
      };
    };
    "import-fresh-3.3.0" = {
      name = "import-fresh";
      packageName = "import-fresh";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-fresh/-/import-fresh-3.3.0.tgz";
        sha512 = "veYYhQa+D1QBKznvhUHxb8faxlrwUnxseDAbAp457E0wLNio2bOSKnjYDhMj+YiAq61xrMGhQk9iXVk5FzgQMw==";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha1 = "9218b9b2b928a238b13dc4fb6b6d576f231453ea";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha1 = "a88c02535791f02ed37c76a1b9ea9773c833f8c2";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "jake-10.8.2" = {
      name = "jake";
      packageName = "jake";
      version = "10.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jake/-/jake-10.8.2.tgz";
        sha512 = "eLpKyrfG3mzvGE2Du8VoPbeSkRry093+tyNjdYaBbJS9v17knImYGNXQCUV0gLxQtF82m3E8iRb/wdSQZLoq7A==";
      };
    };
    "js-yaml-3.14.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.1.tgz";
        sha512 = "okMH7OXXJ7YrN9Ok3/SXrnu4iX9yOk+25nqX4imS2npuvTYDmo/QEZoqwZkYaIDk3jVvBOTOIEgEhaLOynBS9g==";
      };
    };
    "js-yaml-4.1.0" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-4.1.0.tgz";
        sha512 = "wpxZs9NoxZaJESJGIZTyDEaYpl0FKSA+FB9aJiyemKhMwkxQg63h4T1KJgUGHpTqPDNRcmmYLugrRjJlBtWvRA==";
      };
    };
    "json-schema-traverse-0.4.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.4.1.tgz";
        sha512 = "xbbCH5dCYU5T8LcEhhuh7HJ88HXuW3qsI3Y0zOZFKfZEHcpWiHU/Jxzk629Brsab/mMiHQti9wMP+845RPe3Vg==";
      };
    };
    "json-stable-stringify-without-jsonify-1.0.1" = {
      name = "json-stable-stringify-without-jsonify";
      packageName = "json-stable-stringify-without-jsonify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify-without-jsonify/-/json-stable-stringify-without-jsonify-1.0.1.tgz";
        sha1 = "9db7b59496ad3f3cfef30a75142d2d930ad72651";
      };
    };
    "jsonfile-6.1.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-6.1.0.tgz";
        sha512 = "5dgndWOriYSm5cnYaJNhalLNDKOqFwyDB/rr1E9ZsGciGvKPs8R2xYGCacuf3z6K1YKDz182fd+fY3cn3pMqXQ==";
      };
    };
    "levn-0.2.5" = {
      name = "levn";
      packageName = "levn";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.2.5.tgz";
        sha1 = "ba8d339d0ca4a610e3a3f145b9caf48807155054";
      };
    };
    "levn-0.3.0" = {
      name = "levn";
      packageName = "levn";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.3.0.tgz";
        sha1 = "3b09924edf9f083c0490fdd4c0bc4421e04764ee";
      };
    };
    "levn-0.4.1" = {
      name = "levn";
      packageName = "levn";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.4.1.tgz";
        sha512 = "+bT2uH4E5LGE7h/n3evcS/sQlJXCpIp6ym8OWJ5eV6+67Dsql/LaaT7qJBAt2rzfoa/5QBGBhxDix1dMt2kQKQ==";
      };
    };
    "lodash.merge-4.6.2" = {
      name = "lodash.merge";
      packageName = "lodash.merge";
      version = "4.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.merge/-/lodash.merge-4.6.2.tgz";
        sha512 = "0KpjqXRVvrYyCsX1swR/XTK0va6VQkQM6MNo7PqW77ByjAhoARA8EfrP1N4+KlKj8YS0ZUCtRT/YUuhyYDujIQ==";
      };
    };
    "lru-cache-2.5.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-2.5.0.tgz";
        sha1 = "d82388ae9c960becbea0c73bb9eb79b6c6ce9aeb";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "memoizeasync-1.1.0" = {
      name = "memoizeasync";
      packageName = "memoizeasync";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/memoizeasync/-/memoizeasync-1.1.0.tgz";
        sha1 = "9d7028a6f266deb733510bb7dbba5f51878c561e";
      };
    };
    "mimic-fn-2.1.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz";
        sha512 = "OqbOk5oEQeAZ8WXWydlu9HJjz9WVdEIvamMCcXmuqUYjTknH/sqsWvhQ3vgwKFRR1HpjvNBKQ37nbJgYzGqGcg==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "mkdirp-1.0.4" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz";
        sha512 = "vVqVZQyf3WLx2Shd0qJ9xuvqgAyKPLAiqITEtqW0oIUjzo3PePDd6fW9iFz30ef7Ysp/oiWqbhszeGWW2T6Gzw==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "natural-compare-1.4.0" = {
      name = "natural-compare";
      packageName = "natural-compare";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/natural-compare/-/natural-compare-1.4.0.tgz";
        sha1 = "4abebfeed7541f2c27acfb29bdbbd15c8d5ba4f7";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "onetime-5.1.2" = {
      name = "onetime";
      packageName = "onetime";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz";
        sha512 = "kbpaSSGJTWdAY5KPVeMOKXSrPtr8C8C7wodJbcsd51jRnmD+GZu8Y0VoU6Dm5Z4vWr0Ig/1NKuWRKf7j5aaYSg==";
      };
    };
    "optionator-0.3.0" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.3.0.tgz";
        sha1 = "9715a8b5f5e7586cff06c8249e039cd7364d3f54";
      };
    };
    "optionator-0.8.3" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.8.3.tgz";
        sha512 = "+IW9pACdk3XWmmTXG8m3upGUJst5XRGzxMRjXzAuJ1XnIFNvfhjjIuYkDvysnPQ7qzqVzLt78BCruntqRhWQbA==";
      };
    };
    "optionator-0.9.1" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.9.1.tgz";
        sha512 = "74RlY5FCnhq4jRxVUPKDaRwrVNXMqsGsiW6AJw4XK8hmtm10wC0ypZBLw5IIp85NZMr91+qd1RvvENwg7jjRFw==";
      };
    };
    "ot-builder-1.3.0" = {
      name = "ot-builder";
      packageName = "ot-builder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ot-builder/-/ot-builder-1.3.0.tgz";
        sha512 = "FPUhp3BlpGYtjIwngN+7onKCKKR659LO8qajLzJQF48s7EAvqt2JxRZyLesWm9CgI6v0LS+CPyy8MrdKpxmn4Q==";
      };
    };
    "otb-ttc-bundle-1.3.0" = {
      name = "otb-ttc-bundle";
      packageName = "otb-ttc-bundle";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/otb-ttc-bundle/-/otb-ttc-bundle-1.3.0.tgz";
        sha512 = "bb+46cdq0mvvf97Sx4llGxAuzkO7awX4+vdJZFEYFgeu40yHWUSEQBsWRgdsk6//jJ3oIiMiYZOq+qQcz/Wsww==";
      };
    };
    "parent-module-1.0.1" = {
      name = "parent-module";
      packageName = "parent-module";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parent-module/-/parent-module-1.0.1.tgz";
        sha512 = "GQ2EWRpQV8/o+Aw8YqtfZZPfNRWZYkbidE9k5rpl/hC3vtHHBfGm2Ifi6qWV+coDGkrUKZAxE3Lot5kcsRlh+g==";
      };
    };
    "passerror-1.1.1" = {
      name = "passerror";
      packageName = "passerror";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/passerror/-/passerror-1.1.1.tgz";
        sha1 = "a25b88dbdd910a29603aec7dcb96e9a7a97687b4";
      };
    };
    "patel-0.35.1" = {
      name = "patel";
      packageName = "patel";
      version = "0.35.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/patel/-/patel-0.35.1.tgz";
        sha512 = "Em5Zh8t+oVnTNELwze1J9iQEeOBC+84B+UstU4hrmv16uvdunBzmMad6kY28nVxBxycqH6EYsDV2s1rO9IeZaw==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-key-3.1.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
        sha512 = "ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
      };
    };
    "patrisika-0.23.0" = {
      name = "patrisika";
      packageName = "patrisika";
      version = "0.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/patrisika/-/patrisika-0.23.0.tgz";
        sha512 = "bGxKK+XqO7Qfgv7WJSeytwZlbQsKXeuya+FD+6CB0iHat4tSbmN6eT0FEWGf0ulNguD0th/H3fa+VuXDDYQmLw==";
      };
    };
    "patrisika-scopes-0.12.0" = {
      name = "patrisika-scopes";
      packageName = "patrisika-scopes";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/patrisika-scopes/-/patrisika-scopes-0.12.0.tgz";
        sha512 = "rj428KYq5leS75PCDl6iyl91n6/d63yw1ikHYwd1z9UXwWk11Vj2gpTu0CxjLZJJOiFNA01LiX+WMpC5icCKng==";
      };
    };
    "pegjs-0.10.0" = {
      name = "pegjs";
      packageName = "pegjs";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pegjs/-/pegjs-0.10.0.tgz";
        sha1 = "cf8bafae6eddff4b5a7efb185269eaaf4610ddbd";
      };
    };
    "prelude-ls-1.1.2" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz";
        sha1 = "21932a549f5e52ffd9a827f570e04be62a97da54";
      };
    };
    "prelude-ls-1.2.1" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.2.1.tgz";
        sha512 = "vkcDPrRZo1QZLbn5RLGPpg/WmIQ65qoWWhcGKf/b5eplkkarX0m9z8ppCat4mlOqUsWpyNuYgO3VRyrYHSzX5g==";
      };
    };
    "prettier-2.4.1" = {
      name = "prettier";
      packageName = "prettier";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-2.4.1.tgz";
        sha512 = "9fbDAXSBcc6Bs1mZrDYb3XKzDLm4EXXL9sC1LqKP5rZkT6KRr/rf9amVUcODVXgguK/isJz0d0hP72WeaKWsvA==";
      };
    };
    "progress-2.0.3" = {
      name = "progress";
      packageName = "progress";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/progress/-/progress-2.0.3.tgz";
        sha512 = "7PiHtLll5LdnKIMw100I+8xJXR5gW2QwWYkT6iJva0bXitZKa/XMrSbdmg3r2Xnaidz9Qumd0VPaMrZlF9V9sA==";
      };
    };
    "punycode-2.1.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.1.1.tgz";
        sha512 = "XRsRjdf+j5ml+y/6GKHPZbrF/8p2Yga0JPtdqTIY2Xe5ohJPD9saDJJLPvp9+NSBprVvevdXZybnj2cv8OEd0A==";
      };
    };
    "regexpp-3.2.0" = {
      name = "regexpp";
      packageName = "regexpp";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexpp/-/regexpp-3.2.0.tgz";
        sha512 = "pq2bWo9mVD43nbts2wGv17XLiNLya+GklZ8kaDLV2Z08gDCsGpnKn9BFMepvWuHCbyVvY7J5o5+BVvoQbmlJLg==";
      };
    };
    "require-directory-2.1.1" = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha1 = "8c64ad5fd30dab1c976e2344ffe7f792a6a6df42";
      };
    };
    "resolve-from-4.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-4.0.0.tgz";
        sha512 = "pb/MYmXstAkysRFx8piNI1tGFNQIFA3vkE3Gq4EuA1dF6gHp/+vgZqsCGJapvy8N3Q+4o7FwvquPJcnZ7RYy4g==";
      };
    };
    "restore-cursor-3.1.0" = {
      name = "restore-cursor";
      packageName = "restore-cursor";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-3.1.0.tgz";
        sha512 = "l+sSefzHpj5qimhFSE5a8nufZYAM3sBSVMAPtYkmC+4EH2anSGaEMXSD0izRQbu9nfyQ9y5JrVmp7E8oZrUjvA==";
      };
    };
    "resumer-0.0.0" = {
      name = "resumer";
      packageName = "resumer";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resumer/-/resumer-0.0.0.tgz";
        sha1 = "f1e8f461e4064ba39e82af3cdc2a8c893d076759";
      };
    };
    "rimraf-3.0.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz";
        sha512 = "JZkJMZkAGFFPP2YqXZXPbMlMBgsxzE8ILs4lMIX/2o0L9UBw9O/Y3o6wFw/i9YLapcUJWwqbi3kdxIPdC62TIA==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
      };
    };
    "semaphore-async-await-1.5.1" = {
      name = "semaphore-async-await";
      packageName = "semaphore-async-await";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semaphore-async-await/-/semaphore-async-await-1.5.1.tgz";
        sha1 = "857bef5e3644601ca4b9570b87e9df5ca12974fa";
      };
    };
    "semver-6.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz";
        sha512 = "b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==";
      };
    };
    "semver-7.3.5" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.5.tgz";
        sha512 = "PoeGJYh8HK4BTO/a9Tf6ZG3veo/A7ZVsYrSA6J8ny9nb3B1VrpkuN+z9OE5wfE5p6H4LchYZsegiQgbJD94ZFQ==";
      };
    };
    "seq-0.3.5" = {
      name = "seq";
      packageName = "seq";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/seq/-/seq-0.3.5.tgz";
        sha1 = "ae02af3a424793d8ccbf212d69174e0c54dffe38";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "signal-exit-3.0.5" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.5.tgz";
        sha512 = "KWcOiKeQj6ZyXx7zq4YxSMgHRlod4czeBQZrPb8OKcohcqAXShm7E20kEMle9WBt26hFcAf0qLOcp5zmY7kOqQ==";
      };
    };
    "source-map-0.1.43" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.1.43";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.1.43.tgz";
        sha1 = "c24bc146ca517c1471f5dacbe2571b2b7f9e3346";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-0.7.3" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.7.3.tgz";
        sha512 = "CkCj6giN3S+n9qrYiBTX5gystlENnRW5jZeNLHpe6aue+SrHcG5VYwujhW9s4dY31mEGsxBDrHR6oI69fTXsaQ==";
      };
    };
    "source-map-resolve-0.6.0" = {
      name = "source-map-resolve";
      packageName = "source-map-resolve";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-resolve/-/source-map-resolve-0.6.0.tgz";
        sha512 = "KXBr9d/fO/bWo97NXsPIAW1bFSBOuCnjbNTBMO7N59hsv5i9yzRDfcYwwt0l04+VqnKC+EwzvJZIP/qkuMgR/w==";
      };
    };
    "spiro-3.0.0" = {
      name = "spiro";
      packageName = "spiro";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spiro/-/spiro-3.0.0.tgz";
        sha512 = "UEhtLWA8fDQuExOKpT3FLa7Rk238G5Bm3wGAxbvnah3H2X6yEL4blIkAsc38wNwMXBwQFRYE6l0Q9X0t1izOxA==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "strip-json-comments-3.1.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-3.1.1.tgz";
        sha512 = "6fPc+R4ihwqP6N/aIv2f1gMH8lOVtWQHoqC4yK6oSDVVocumAsfCqjkXnqiYMhmMwS/mEHLp7Vehlt3ql6lEig==";
      };
    };
    "stylus-0.55.0" = {
      name = "stylus";
      packageName = "stylus";
      version = "0.55.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylus/-/stylus-0.55.0.tgz";
        sha512 = "MuzIIVRSbc8XxHH7FjkvWqkIcr1BvoMZoR/oFuAJDlh7VSaNJzrB4uJ38GRQa+mWjLXODAMzeDe0xi9GYbGwnw==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "text-table-0.2.0" = {
      name = "text-table";
      packageName = "text-table";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/text-table/-/text-table-0.2.0.tgz";
        sha1 = "7f5ee823ae805207c00af2df4a84ec3fcfa570b4";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "toposort-2.0.2" = {
      name = "toposort";
      packageName = "toposort";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/toposort/-/toposort-2.0.2.tgz";
        sha1 = "ae21768175d1559d48bef35420b2f4962f09c330";
      };
    };
    "traverse-0.3.9" = {
      name = "traverse";
      packageName = "traverse";
      version = "0.3.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/traverse/-/traverse-0.3.9.tgz";
        sha1 = "717b8f220cc0bb7b44e40514c22b2e8bbc70d8b9";
      };
    };
    "tslib-2.3.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.3.1.tgz";
        sha512 = "77EbyPPpMz+FRFRuAFlWMtmgUWGe9UOG2Z25NqCwiIjRhOf5iKGuzSe5P2w1laq+FkRy4p+PCuVkJSGkzTEKVw==";
      };
    };
    "type-check-0.3.2" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.3.2.tgz";
        sha1 = "5884cab512cf1d355e3fb784f30804b2b520db72";
      };
    };
    "type-check-0.4.0" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.4.0.tgz";
        sha512 = "XleUoc9uwGXqjWwXaUTZAmzMcFZ5858QA2vvx1Ur5xIcixXIP+8LnFDgRplU30us6teqdlskFfu+ae4K79Ooew==";
      };
    };
    "type-fest-0.20.2" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "0.20.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-0.20.2.tgz";
        sha512 = "Ne+eE4r0/iWnpAxD852z3A+N0Bt5RN//NjJwRd2VFHEmrywxf5vsZlh4R6lixl6B+wz/8d+maTSAkN1FIkI3LQ==";
      };
    };
    "typo-geom-0.12.1" = {
      name = "typo-geom";
      packageName = "typo-geom";
      version = "0.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/typo-geom/-/typo-geom-0.12.1.tgz";
        sha512 = "W20RYp2OCEGMhEYayR0cAP67AUWiGRUufMs6Clul7MAmu5SpLuOG/RWk7+LkL65wsugcfhPQlFEJ231C2xHNQg==";
      };
    };
    "unicoderegexp-0.4.1" = {
      name = "unicoderegexp";
      packageName = "unicoderegexp";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unicoderegexp/-/unicoderegexp-0.4.1.tgz";
        sha1 = "afb10e4ef1eeddc711417bbb652bc885da9d4171";
      };
    };
    "universalify-2.0.0" = {
      name = "universalify";
      packageName = "universalify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-2.0.0.tgz";
        sha512 = "hAZsKq7Yy11Zu1DE0OzWjw7nnLZmJZYTDZZyEFHZdUhV8FkH5MCfoU1XMaxXovpyW5nq5scPqq0ZDP9Zyl04oQ==";
      };
    };
    "uri-js-4.4.1" = {
      name = "uri-js";
      packageName = "uri-js";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-js/-/uri-js-4.4.1.tgz";
        sha512 = "7rKUyy33Q1yc98pQ1DAmLtwX109F7TIfWlW1Ydo8Wl1ii1SeHieeh0HHfPeL2fMXK6z0s8ecKs9frCuLJvndBg==";
      };
    };
    "v8-compile-cache-2.3.0" = {
      name = "v8-compile-cache";
      packageName = "v8-compile-cache";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/v8-compile-cache/-/v8-compile-cache-2.3.0.tgz";
        sha512 = "l8lCEmLcLYZh4nbunNZvQCJc5pv7+RCwa8q/LdUx8u7lsWvPDKmpodJAJNwkAhJC//dFY48KuIEmjtd4RViDrA==";
      };
    };
    "verda-1.4.0" = {
      name = "verda";
      packageName = "verda";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verda/-/verda-1.4.0.tgz";
        sha512 = "XzAxyH/99hE4B729ImVqv3TBYxDYwMsjVB8q4fIBOMtnsY9hvrT4xmiim9cRvwyKpCkF2uysyVbeMbFRqN3qgw==";
      };
    };
    "wawoff2-2.0.0" = {
      name = "wawoff2";
      packageName = "wawoff2";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wawoff2/-/wawoff2-2.0.0.tgz";
        sha512 = "5gjFj+fyQO9cMrg5vYaVM7+T37xSHpqUWM/S6UCEiBx8wRmfpvuhYjPM3toB2UujpmWQt1hSPKRo/jIRE/j9Eg==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "word-wrap-1.2.3" = {
      name = "word-wrap";
      packageName = "word-wrap";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/word-wrap/-/word-wrap-1.2.3.tgz";
        sha512 = "Hz/mrNwitNRh/HUAtM/VT/5VH+ygD6DV7mYKZAtHOrbs8U7lvPS6xf7EJKMF0uW1KJCl0H701g3ZGus+muE5vQ==";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "wrap-ansi-7.0.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
        sha512 = "YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "xpath-0.0.32" = {
      name = "xpath";
      packageName = "xpath";
      version = "0.0.32";
      src = fetchurl {
        url = "https://registry.npmjs.org/xpath/-/xpath-0.0.32.tgz";
        sha512 = "rxMJhSIoiO8vXcWvSifKqhvV96GjiD5wYb8/QHdoRyQvraTpp4IEv944nhGausZZ3u7dhQXteZuZbaqfpB7uYw==";
      };
    };
    "y18n-5.0.8" = {
      name = "y18n";
      packageName = "y18n";
      version = "5.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-5.0.8.tgz";
        sha512 = "0pfFzegeDWJHJIAmTLRP2DwHjdF5s7jo9tuztdQxAhINCdvS+3nGINqPd00AphqJR/0LhANUS6/+7SCb98YOfA==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "yargs-16.2.0" = {
      name = "yargs";
      packageName = "yargs";
      version = "16.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-16.2.0.tgz";
        sha512 = "D1mvvtDG0L5ft/jGWkLpG1+m0eQxOfaBvTNELraWj22wSVUMWxZUvYgJYcKh6jGGIkJFhH4IZPQhR4TKpc8mBw==";
      };
    };
    "yargs-17.2.1" = {
      name = "yargs";
      packageName = "yargs";
      version = "17.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-17.2.1.tgz";
        sha512 = "XfR8du6ua4K6uLGm5S6fA+FIJom/MdJcFNVY8geLlp2v8GYbOXD4EB1tPNZsRn4vBzKGMgb5DRZMeWuFc2GO8Q==";
      };
    };
    "yargs-parser-20.2.9" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "20.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-20.2.9.tgz";
        sha512 = "y11nGElTIV+CT3Zv9t7VKl+Q3hTQoT9a1Qzezhhl6Rp21gJ/IVTW7Z3y9EWXhuUBC2Shnf+DX0antecpAwSP8w==";
      };
    };
  };
  args = {
    name = "iosevka";
    packageName = "iosevka";
    version = "10.3.4";
    src = ./.;
    dependencies = [
      (sources."@eslint/eslintrc-1.0.3" // {
        dependencies = [
          sources."argparse-1.0.10"
          sources."debug-4.3.2"
          sources."js-yaml-3.14.1"
          sources."ms-2.1.2"
        ];
      })
      (sources."@humanwhocodes/config-array-0.6.0" // {
        dependencies = [
          sources."debug-4.3.2"
          sources."ms-2.1.2"
        ];
      })
      sources."@humanwhocodes/object-schema-1.2.0"
      sources."@iarna/toml-2.2.5"
      sources."@msgpack/msgpack-2.7.1"
      sources."@ot-builder/bin-composite-types-1.3.0"
      sources."@ot-builder/bin-util-1.3.0"
      (sources."@ot-builder/cli-help-shower-1.3.0" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
          sources."chalk-4.1.2"
          sources."color-convert-2.0.1"
          sources."color-name-1.1.4"
          sources."has-flag-4.0.0"
          sources."supports-color-7.2.0"
        ];
      })
      sources."@ot-builder/cli-proc-1.3.0"
      sources."@ot-builder/cli-shared-1.3.0"
      sources."@ot-builder/common-impl-1.3.0"
      sources."@ot-builder/errors-1.3.0"
      sources."@ot-builder/io-bin-cff-1.3.0"
      sources."@ot-builder/io-bin-encoding-1.3.0"
      sources."@ot-builder/io-bin-ext-private-1.3.0"
      sources."@ot-builder/io-bin-font-1.3.0"
      sources."@ot-builder/io-bin-glyph-store-1.3.0"
      sources."@ot-builder/io-bin-layout-1.3.0"
      sources."@ot-builder/io-bin-metadata-1.3.0"
      sources."@ot-builder/io-bin-metric-1.3.0"
      sources."@ot-builder/io-bin-name-1.3.0"
      sources."@ot-builder/io-bin-sfnt-1.3.0"
      sources."@ot-builder/io-bin-ttf-1.3.0"
      sources."@ot-builder/io-bin-vtt-private-1.3.0"
      sources."@ot-builder/ot-1.3.0"
      sources."@ot-builder/ot-encoding-1.3.0"
      sources."@ot-builder/ot-ext-private-1.3.0"
      sources."@ot-builder/ot-glyphs-1.3.0"
      sources."@ot-builder/ot-layout-1.3.0"
      sources."@ot-builder/ot-metadata-1.3.0"
      sources."@ot-builder/ot-name-1.3.0"
      sources."@ot-builder/ot-sfnt-1.3.0"
      sources."@ot-builder/ot-standard-glyph-namer-1.3.0"
      sources."@ot-builder/ot-vtt-private-1.3.0"
      sources."@ot-builder/prelude-1.3.0"
      sources."@ot-builder/primitive-1.3.0"
      sources."@ot-builder/rectify-1.3.0"
      sources."@ot-builder/stat-glyphs-1.3.0"
      sources."@ot-builder/trace-1.3.0"
      sources."@ot-builder/var-store-1.3.0"
      sources."@ot-builder/variance-1.3.0"
      sources."@unicode/unicode-13.0.0-1.2.1"
      sources."@xmldom/xmldom-0.7.5"
      sources."acorn-8.5.0"
      sources."acorn-jsx-5.3.2"
      sources."aglfn-1.0.2"
      sources."ajv-6.12.6"
      sources."amdefine-1.0.1"
      sources."ansi-colors-4.1.1"
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-3.2.1"
      sources."argparse-2.0.1"
      sources."async-0.9.2"
      sources."atob-2.1.2"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-1.1.11"
      sources."callsites-3.1.0"
      sources."chainsaw-0.0.9"
      sources."chalk-2.4.2"
      sources."cldr-7.1.1"
      sources."cli-cursor-3.1.0"
      sources."clipper-lib-6.4.2"
      sources."cliui-7.0.4"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."concat-map-0.0.1"
      sources."cross-spawn-7.0.3"
      sources."css-3.0.0"
      sources."debug-3.1.0"
      sources."decode-uri-component-0.2.0"
      sources."deep-is-0.1.4"
      sources."doctrine-3.0.0"
      sources."ejs-3.1.6"
      sources."emoji-regex-8.0.0"
      sources."enquirer-2.3.6"
      sources."escalade-3.1.1"
      sources."escape-string-regexp-1.0.5"
      sources."escodegen-2.0.0"
      (sources."escope-1.0.3" // {
        dependencies = [
          sources."estraverse-2.0.0"
        ];
      })
      (sources."eslint-8.0.1" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
          sources."chalk-4.1.2"
          sources."color-convert-2.0.1"
          sources."color-name-1.1.4"
          sources."debug-4.3.2"
          sources."escape-string-regexp-4.0.0"
          sources."has-flag-4.0.0"
          sources."levn-0.4.1"
          sources."ms-2.1.2"
          sources."optionator-0.9.1"
          sources."prelude-ls-1.2.1"
          sources."supports-color-7.2.0"
          sources."type-check-0.4.0"
        ];
      })
      sources."eslint-config-prettier-8.3.0"
      sources."eslint-scope-6.0.0"
      (sources."eslint-utils-3.0.0" // {
        dependencies = [
          sources."eslint-visitor-keys-2.1.0"
        ];
      })
      sources."eslint-visitor-keys-3.0.0"
      (sources."esmangle-1.0.1" // {
        dependencies = [
          sources."escodegen-1.3.3"
          sources."esprima-1.1.1"
          sources."estraverse-1.5.1"
          sources."esutils-1.0.0"
          sources."fast-levenshtein-1.0.7"
          sources."levn-0.2.5"
          sources."optionator-0.3.0"
          sources."source-map-0.1.43"
        ];
      })
      sources."espree-9.0.0"
      sources."esprima-4.0.1"
      sources."esquery-1.4.0"
      sources."esrecurse-4.3.0"
      (sources."esshorten-1.1.1" // {
        dependencies = [
          sources."estraverse-4.1.1"
        ];
      })
      sources."estraverse-5.2.0"
      sources."esutils-2.0.3"
      sources."fast-deep-equal-3.1.3"
      sources."fast-json-stable-stringify-2.1.0"
      sources."fast-levenshtein-2.0.6"
      sources."file-entry-cache-6.0.1"
      sources."filelist-1.0.2"
      sources."flat-cache-3.0.4"
      sources."flatted-3.2.2"
      sources."fs-extra-10.0.0"
      sources."fs.realpath-1.0.0"
      sources."functional-red-black-tree-1.0.1"
      sources."get-caller-file-2.0.5"
      sources."glob-7.2.0"
      sources."glob-parent-6.0.2"
      sources."globals-13.11.0"
      sources."graceful-fs-4.2.8"
      sources."has-flag-3.0.0"
      sources."hashish-0.0.4"
      sources."iconv-lite-0.6.3"
      sources."ignore-4.0.6"
      sources."import-fresh-3.3.0"
      sources."imurmurhash-0.1.4"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."is-extglob-2.1.1"
      sources."is-fullwidth-code-point-3.0.0"
      sources."is-glob-4.0.3"
      sources."isexe-2.0.0"
      sources."jake-10.8.2"
      sources."js-yaml-4.1.0"
      sources."json-schema-traverse-0.4.1"
      sources."json-stable-stringify-without-jsonify-1.0.1"
      sources."jsonfile-6.1.0"
      sources."levn-0.3.0"
      sources."lodash.merge-4.6.2"
      sources."lru-cache-2.5.0"
      sources."memoizeasync-1.1.0"
      sources."mimic-fn-2.1.0"
      sources."minimatch-3.0.4"
      sources."mkdirp-1.0.4"
      sources."ms-2.0.0"
      sources."natural-compare-1.4.0"
      sources."once-1.4.0"
      sources."onetime-5.1.2"
      sources."optionator-0.8.3"
      sources."ot-builder-1.3.0"
      sources."otb-ttc-bundle-1.3.0"
      sources."parent-module-1.0.1"
      sources."passerror-1.1.1"
      sources."patel-0.35.1"
      sources."path-is-absolute-1.0.1"
      sources."path-key-3.1.1"
      sources."patrisika-0.23.0"
      sources."patrisika-scopes-0.12.0"
      sources."pegjs-0.10.0"
      sources."prelude-ls-1.1.2"
      sources."prettier-2.4.1"
      sources."progress-2.0.3"
      sources."punycode-2.1.1"
      sources."regexpp-3.2.0"
      sources."require-directory-2.1.1"
      sources."resolve-from-4.0.0"
      sources."restore-cursor-3.1.0"
      sources."resumer-0.0.0"
      sources."rimraf-3.0.2"
      sources."safer-buffer-2.1.2"
      sources."sax-1.2.4"
      sources."semaphore-async-await-1.5.1"
      (sources."semver-7.3.5" // {
        dependencies = [
          sources."lru-cache-6.0.0"
        ];
      })
      sources."seq-0.3.5"
      sources."shebang-command-2.0.0"
      sources."shebang-regex-3.0.0"
      sources."signal-exit-3.0.5"
      sources."source-map-0.6.1"
      sources."source-map-resolve-0.6.0"
      sources."spiro-3.0.0"
      sources."sprintf-js-1.0.3"
      sources."string-width-4.2.3"
      sources."strip-ansi-6.0.1"
      sources."strip-json-comments-3.1.1"
      (sources."stylus-0.55.0" // {
        dependencies = [
          sources."semver-6.3.0"
          sources."source-map-0.7.3"
        ];
      })
      sources."supports-color-5.5.0"
      sources."text-table-0.2.0"
      sources."through-2.3.8"
      sources."toposort-2.0.2"
      sources."traverse-0.3.9"
      sources."tslib-2.3.1"
      sources."type-check-0.3.2"
      sources."type-fest-0.20.2"
      sources."typo-geom-0.12.1"
      sources."unicoderegexp-0.4.1"
      sources."universalify-2.0.0"
      sources."uri-js-4.4.1"
      sources."v8-compile-cache-2.3.0"
      (sources."verda-1.4.0" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
          sources."chalk-4.1.2"
          sources."color-convert-2.0.1"
          sources."color-name-1.1.4"
          sources."has-flag-4.0.0"
          sources."supports-color-7.2.0"
          sources."yargs-17.2.1"
        ];
      })
      sources."wawoff2-2.0.0"
      sources."which-2.0.2"
      sources."word-wrap-1.2.3"
      sources."wordwrap-0.0.3"
      (sources."wrap-ansi-7.0.0" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
          sources."color-convert-2.0.1"
          sources."color-name-1.1.4"
        ];
      })
      sources."wrappy-1.0.2"
      sources."xpath-0.0.32"
      sources."y18n-5.0.8"
      sources."yallist-4.0.0"
      sources."yargs-16.2.0"
      sources."yargs-parser-20.2.9"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
