# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" "acpi_call" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.acpi_call ];

  boot.blacklistedKernelModules = [ "mei_wdt" ];

  boot.initrd.luks.devices = {
    root = {
      device = "/dev/nvme0n1p3";
      preLVM = true;
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0e6b04ce-6b3e-4b25-b825-f563182acad8";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0156-EE6F";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ccf99d96-352f-41c6-b9b5-1802c1449ad8"; }
    ];

  nix = {
    buildCores = 4;
    maxJobs = 4;
  };

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # Fixes 'TSC_DEADLINE disabled due to Errata' message
  # Must be kept enabled, needs to take effect on every boot
  hardware.cpu.intel.updateMicrocode = true;
}
