#!/bin/sh
set -e

cd /tmp

# see https://github.com/Airblader/i3/wiki/Compiling-&-Installing
sudo apt-get install \
  libxcb1-dev \
  libxcb-keysyms1-dev \
  libpango1.0-dev \
  libxcb-util0-dev \
  libxcb-icccm4-dev \
  libyajl-dev \
  libstartup-notification0-dev \
  libxcb-randr0-dev \
  libev-dev \
  libxcb-cursor-dev \
  libxcb-xinerama0-dev \
  libxcb-xkb-dev \
  libxkbcommon-dev \
  libxkbcommon-x11-dev


git clone git@github.com:Airblader/i3.git
cd i3

# stable branch is gaps, unstable is gaps-next (corresponding to master and next)
git checkout gaps-next

make

sudo make install
