#!/bin/bash

set -e
pushd ~

for DOTFILE in .zshrc .zsh .gitconfig .i3 .profile .urxvt .vim .vimperatorrc .vimrc .Xresources .Xresources.d; do
  if [ -e $DOTFILE ]; then mv $DOTFILE "$DOTFILE.bak"; fi
  ln -s "config-files/$DOTFILE"
done
