#!/usr/bin/env bash

set -e
cd ~

for DOTFILE in .compton.conf \
               .gitconfig \
               .i3 \
               .profile \
               .tigrc \
               .urxvt \
               .vim \
               .vimperatorrc \
               .vimrc \
               .Xresources \
               .Xresources.d \
               .zsh \
               .zshrc; do
  if [ -e $DOTFILE ]; then
    if [ -h $DOTFILE ]; then rm $DOTFILE
    else                     mv $DOTFILE "$DOTFILE.bak"
    fi
  fi
  ln -s "config-files/$DOTFILE"
done
