#!/bin/bash
set -e

VERSION=2.1.1

# If ./configure fails or all the Unicode characters are wrong
# sudo apt-get install libncursesw5-dev

cd /tmp
wget "http://jonas.nitro.dk/tig/releases/tig-2.1.1.tar.gz"
tar -xzf "tig-${VERSION}.tar.gz"
cd "tig-$VERSION"

./configure
make
make doc-man
sudo make install
sudo make install-doc-man

sudo cp contrib/tig-completion.bash /etc/bash_completion.d/tig
