#!/usr/bin/env bash

item=${1:-sink}

function active_item() {
  pacmd list-${item}s \
    | grep "* index" \
    | awk '{print $3}'
}

function is_muted() {
  sink=$1
  pacmd list-${item}s \
    | awk "/index: ${sink}/,/active port/" \
    | grep "muted" | grep "yes"

}

function current_vol() {
  id=$1
  pacmd dump-volumes \
    | grep -i "${item} ${id}" \
    | sed 's/, /\n/g' \
    | grep reference \
    | tr ' ' '\n' \
    | grep '%' \
    | sed 's/%//'
}

function toggle_mute() {
  id=$1
  if [ -n "$( is_muted $id )" ]; then
    pacmd set-${item}-mute "$id" off
  else
    pacmd set-${item}-mute "$id" on
  fi
}


ACTIVE=$( active_item )

[ "${BLOCK_BUTTON:-0}" -eq "1" ] && toggle_mute "$ACTIVE"

CURRENT_VOL="$( current_vol $ACTIVE )%"
IS_MUTED=$( is_muted $ACTIVE )

case $item in
  sink)
    if [ -n "$IS_MUTED" ]; then
      echo "<span bgcolor='#dc322f' color='#fdf6e3'>  MUTE </span>"
    else
      echo " <span color='#cb4b16'></span> ${CURRENT_VOL} "
    fi
    ;;
  source)
    if [ -n "$IS_MUTED" ]; then
      echo "<span bgcolor='#dc322f' color='#fdf6e3'>  MUTE </span>"
    else
      echo " <span color='#cb4b16'></span> ${CURRENT_VOL} "
    fi
    ;;
esac
