#!/bin/bash

[ "${BLOCK_BUTTON}" -eq "1" ] && (
  CONN=$(nmcli -t -f name connection | dmenu -i)
  nmcli connection up "$CONN"
) &

[ "${BLOCK_BUTTON}" -eq "2" ] && (
  CONN=$(nmcli -t -f name connection show --active | dmenu -i)
  nmcli connection down "$CONN"
) &

[ "${BLOCK_BUTTON}" -eq "3" ] && (
  SSID=$(nmcli -t -f SSID device wifi | dmenu -i)
  nmcli device wifi connect "$SSID"
) &

function connection_of_type() {
  nmcli -t -f type,name connection show --active \
    | grep $1 \
    | awk -F: '{print $2}'
}

WIRELESS="$(connection_of_type wireless)"
VPN="$(connection_of_type vpn)"
[ -n "$WIRELESS" ] \
  && echo -n "   ${WIRELESS} " \
  || echo -n "   ---"
[ -n "$VPN" ] \
  && echo -n "   ${VPN} "
echo
