#!/usr/bin/env bash

violet="#6c71c4"

[ "${BLOCK_BUTTON:-0}" -eq "1" ] && nm-connect &
[ "${BLOCK_BUTTON:-0}" -eq "2" ] && nm-disconnect &
[ "${BLOCK_BUTTON:-0}" -eq "3" ] && nm-wifi &

function connections_of_type() {
  nmcli -t -f type,name connection show --active \
    | grep $1 \
    | awk -F: '{print $2}'
}

connections_of_type ethernet | while read ETHERNET; do
  [ -n "$ETHERNET" ] \
    && echo -n "  <span color='$violet'></span> ${ETHERNET} "
done

connections_of_type wireless | while read WIRELESS; do
  [ -n "$WIRELESS" ] \
    && echo -n "  <span color='$violet'></span> ${WIRELESS} "
done

connections_of_type vpn | while read VPN; do
  [ -n "$VPN" ] \
    && echo -n "  <span color='$violet'></span> ${VPN} "
done

echo ""
